namespace: "uatljjl"
catalogue:
    image:
        repo: weaveworksdemos/catalogue
        tag: 0.3.5
    containerPort: 80
    resources:
        limits:
            cpu: 100m
            memory: 100Mi
        requests:
            cpu: 100m
            memory: 100Mi